### ISSUE TITLE
无法显示点赞标志

### ISSUE THREAD

**Issue by chronosAeon** [ifanrx/brick-layout#11]
liked填写但是没有大拇指的标志。

**Comment by XCifer** [comment]
dataset里面每一项的likedCount也要填

**Comment by XCifer** [comment]
> liked填写但是没有大拇指的标志。

dataset里面每一项的likedCount也要填

**Comment by XCifer** [comment]
> liked填写但是没有大拇指的标志。

dataset里面每一项的likedCount也要填

**Comment by haihonglicom** [comment]
暂无维护计划，欢迎 PR
