### ISSUE TITLE
支持仅图片展示的瀑布流吗

### ISSUE THREAD

**Issue by lemontreezj** [ifanrx/brick-layout#19]
![1602488321(1)](https://user-images.githubusercontent.com/22071231/95718455-10705f80-0ca1-11eb-8951-88b418b445de.jpg)

**Comment by ElanYoung** [comment]
同问

**Comment by csm0522** [comment]
你好，设计之初是有考虑到这种场景的，可以看看 components/tpl/tpl-album.wxml 里面的内容。尝试调整模板试试看。
