### ISSUE TITLE
未使用自定义组件方式，setData后计算高度不准 有很多固定值

### ISSUE THREAD

**Issue by raochuan** [ifanrx/brick-layout#9]
this.setData({ renderList }, () => {
        setTimeout(() => {
          that._computeCardHeight()
        }, 0)
      })

setTimeOut 时长设置500为基本正常

计算出来的高度 都会固定值302

**Comment by heshiyou** [comment]
这个和设备性能以及当时的负载关系比较大，有劳提供下你当时的设备型号。

**Comment by raochuan** [comment]
数据量比较大，设备是用的模拟器，可能跟你说的负载有关系，setData的回调能保证文字等渲染完成，图片渲染不一定吧

**Comment by Jinchengawu** [comment]
_computeCardHeight()里边调用了 _computeSingleCardHeight()
 _computeSingleCardHeight()里边调用了 wx.createSelectorQuery()
wx.createSelectorQuery() 当前元素如果没有被内容撑开 就会获取高度不正确；
wx.createSelectorQuery() 获取不准确，这个问题我在很多地方都遇到过

**Comment by shisongsong** [comment]
@Jinchengawu 那这种情况怎么搞嘞，今天也遇到了，计算出来的高度都是240

**Comment by haihonglicom** [comment]
建议在滚动的时候重新计算

暂无维护计划，欢迎 PR
